### PR TITLE
Add programs & content from some Solstices

### PR DESCRIPTION
**Pull request by mwerbos**
I've run a few small Solstices now and wanted to add the content I've been using.

@Raemon could you take a look at the disclaimer I added to the Stonehenge story and make sure you're ok with it?

Also -- one thing I wasn't sure about -- I had a couple programs where there were several Litanies of Tarski, and it would be nice to be able to specify which one was at each point in the program. Is there some way to add a note/comment to a program for that kind of thing?

(apologies if I made any Github faux pas, I've never actually made a PR to a repo I don't own before)

### CODE REVIEW

**Comment by Raemon** [comment]
I would instead say "some of the facts about stonehenge are misleading" rather than "inaccurate." I was actually careful to only say true things the first time around, but the combination of true things I said implies some _other_ things which are false. 

(Basically: Stonehenge is a legitimately great work that required a ton of effort to produce and is a valuable symbol of ancient humans working on hard projects they wouldn't live to see the end of. It's *also* IMO most likely to be oriented around the Winter Solstice, most likely because Winter Solstice was legitimately important for the reasons I said, which makes it a valuable symbol of the Solstice. But, I think these two symbolisms are mostly unrelated, rather that sensible to intertwine as a single narrative)

**Comment by dspeyer** [comment]
Merged.

Litanies of Tarski: Yes, if you follow a speech with a colon and a note,
the note will appear in the program,  See Boston 2013 for an example.

Was Solstice Under The Sky also Washington DC?  I'm inclined to tweak the
name to fit the conventions of the program list.

**Comment by mwerbos** [comment]
Solstice Under the Sky was another outdoor solstice in the Bay Area in 2016.

**Comment by dspeyer** [comment]
Then this is the same one already there as Bay Outdoor 2016 -- except there
are a few differences.

Given how live speaking goes, I'm not too concerned about whether Story of
Winter or Stonehenge Story is the more accurate text.  And it's good to
fill in Fire Has No Voice.

It'd be good to be confident about whether Lean On Me was sung in between
Uplift and Still Alive.

**Comment by mwerbos** [comment]
No, it's not. I ran a separate Solstice that year from the one Ray did. Interesting to hear that there was a lot of overlap in content, that was not coordinated at all.

**Comment by Raemon** [comment]
I thought I didn't do Solstice in the woods until after the year you did?
(I thought I was inspired by you). My guess is Daniel made some guesses
based on stuff he heard and made assumptions.

**Comment by mwerbos** [comment]
Huh... Okay, it looks like this actually is the same thing? I am confused, since it seems @dspeyer committed this to the repo and I'm not sure how my program got to him in the first place. Maybe I asked him to put it in for me and forgot?

Anyway, we should in fact consolidate them. I can double check my paper version of the program to see if Lean on Me ended up in there.

**Comment by dspeyer** [comment]
The solstice Ray ran in 2016 was the NYC Story of Smallpox solstice.  I'd
be very surprised if he ran anything in the Bay that year, since he
couldn't have spent that much time there.

I also don't believe that two events that similar happened in the same city
in the same year by co-incidence.

I'm 90% common that I copied the Bay Outdoor 2016 page off of
https://docs.google.com/document/d/13YSsK7XnGL7b04_eODGc8ynCJb__lb4zRofzvB46OWM/edit
linked from
https://www.facebook.com/groups/158117984552696/permalink/566628493701641/
both of which explicitly identify it as yours (Maia's).  I base this in
large part on having committed that file three days after you left that
comment.

Changing the poetic "Solstice under the Sky" to the shorter "Outdoor" was
my doing, mostly to make web layout look good.  Dropping Lean on Me appears
to have just been my mistake (though I was pretty careful, so maybe there
was reason to think it wasn't sung which I have since forgotten?).

Now I'm wondering if it would be worth putting organizer names on
solstices.  My gut feeling is no, but it would have helped here.

**Comment by mwerbos** [comment]
Yep, clearly you're right. I didn't look at the program / didn't know the Solstice I ran had been committed to the repo already.

Bay Outdoor 2016 seems like a fine name for it.

I just tried to dig up a paper copy of the program and couldn't immediately find it... but my best guess is that Lean On Me was in fact in there.

**Pull request merged**
